//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Secure')
export class SecureEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('date', { nullable: true })
  lastSecurityUpdate: Date;
}
