//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Secure: [
      { lastSecurityUpdate: '2023-04-28T14:55:05.713Z', id: 27 },
      { lastSecurityUpdate: '2023-04-29T18:29:09.152Z', id: 5 },
      { lastSecurityUpdate: '2025-01-12T12:58:01.798Z', id: 4 },
      { lastSecurityUpdate: '2024-07-02T23:58:35.541Z', id: 9 },
      { lastSecurityUpdate: '2024-09-22T17:09:57.878Z', id: 75 },
    ],
  },
};
export default data;
